import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

// Set these two public project values in config.js after creating your Supabase project.
import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';
const $ = (s, root=document) => root.querySelector(s), $$ = (s, root=document) => [...root.querySelectorAll(s)];
const fmt = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0);
const isoToday = () => new Date().toISOString().slice(0,10);
const escapeHtml = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaultCategories = ['Food & dining','Transport','Shopping','Housing','Bills','Health','Education','Entertainment','Travel','Personal care','Other'];
let db, user, appBound=false, state={page:'dashboard',period:'month',transactions:[],budgets:[],goals:[],recurring:[],subscriptions:[],categories:defaultCategories,accounts:[],search:'',filter:'all',settingsTab:'categories'};
const pages={dashboard:'Overview',transactions:'Transactions',budgets:'Budgets',goals:'Goals',recurring:'Recurring',subscriptions:'Subscriptions',reports:'Reports',settings:'Settings'};

function message(text, error=false, target='#global-message'){const box=$(target);box.textContent=text;box.classList.remove('hidden','error');if(error)box.classList.add('error');setTimeout(()=>box.classList.add('hidden'),5000)}
function configReady(){return SUPABASE_URL.startsWith('https://')&&SUPABASE_ANON_KEY.length>20}
async function init(){
  if(!configReady()){ $('#auth-screen').classList.remove('hidden'); $('#auth-message').textContent='Add your Supabase project URL and anon key to config.js, then reload.';$('#auth-message').classList.remove('hidden');$('#auth-form').classList.add('hidden');$('#auth-toggle').classList.add('hidden');return; }
  db=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);const {data:{session}}=await db.auth.getSession();if(session)await startApp(session.user);
  db.auth.onAuthStateChange(async(_event,session)=>{if(session)await startApp(session.user);else showAuth()});
  $('#auth-form').addEventListener('submit',authSubmit);$('#auth-toggle').addEventListener('click',()=>{state.signUp=!state.signUp;$('#auth-submit').textContent=state.signUp?'Create account':'Sign in';$('#auth-toggle').textContent=state.signUp?'Already have an account? Sign in':'New to Ledgerly? Create an account';$('#auth-password').autocomplete=state.signUp?'new-password':'current-password';});
}
function showAuth(){$('#app').classList.add('hidden');$('#auth-screen').classList.remove('hidden')}
async function authSubmit(e){e.preventDefault();const email=$('#auth-email').value.trim(),password=$('#auth-password').value;$('#auth-submit').disabled=true;try{const result=state.signUp?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(state.signUp&&!result.data.session){$('#auth-message').textContent='Check your email to confirm your account, then sign in.';$('#auth-message').classList.remove('hidden','error')}else if(result.data.session)await startApp(result.data.user)}catch(err){$('#auth-message').textContent=err.message;$('#auth-message').classList.remove('hidden');$('#auth-message').classList.add('error')}finally{$('#auth-submit').disabled=false}}
async function startApp(nextUser){user=nextUser;$('#auth-screen').classList.add('hidden');$('#app').classList.remove('hidden');$('#user-email').textContent=user.email;if(!appBound){bindApp();appBound=true}await loadAll();render()}
function bindApp(){
  $('#navigation').onclick=e=>{const b=e.target.closest('[data-page]');if(b)go(b.dataset.page)};
  $('#quick-add').onclick=()=>openTransaction();$('#signout').onclick=async()=>{await db.auth.signOut()};$('#menu-toggle').onclick=()=>$('.sidebar').classList.toggle('open');$('#period-select').onchange=e=>{state.period=e.target.value;render()};
  $('#transaction-form').onsubmit=saveTransaction;$('#simple-form').onsubmit=saveSimple;
  document.addEventListener('click',async e=>{const close=e.target.closest('[data-close]');if(close){close.closest('dialog').close();return}const action=e.target.closest('[data-action]');if(action)await handleAction(action.dataset.action,action.dataset.id,action.dataset.kind);const page=e.target.closest('[data-goto]');if(page)go(page.dataset.goto);});
  $('#page-content').addEventListener('input',e=>{if(e.target.id==='transaction-search'){const pos=e.target.selectionStart;state.search=e.target.value;renderTransactions();const input=$('#transaction-search');input.focus();input.setSelectionRange(pos,pos)} });
  $('#page-content').addEventListener('change',e=>{if(e.target.id==='transaction-filter'){state.filter=e.target.value;renderTransactions()}});
  $('#confirm-action').onclick=e=>{e.preventDefault();const d=$('#confirm-dialog');d.close('confirm');if(state.pendingDelete)deleteItem(...state.pendingDelete);};
}
async function loadAll(){const tables=['transactions','budgets','goals','recurring','subscriptions','categories','accounts'];const results=await Promise.all(tables.map(t=>db.from(t).select('*').order('created_at',{ascending:false})));for(let i=0;i<tables.length;i++){if(results[i].error){message(`Could not load ${tables[i]}: ${results[i].error.message}`,true);continue}state[tables[i]]=results[i].data||[]}if(!state.categories.length)state.categories=defaultCategories.map(name=>({id:null,name}));}
function go(page){state.page=page;$('.sidebar').classList.remove('open');render()}
function render(){ $('#page-title').textContent=pages[state.page]||'Overview';$('#today-label').textContent=new Intl.DateTimeFormat('en-IN',{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase();$('#period-select').value=state.period;$$('.nav-item[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));const renderers={dashboard:renderDashboard,transactions:renderTransactions,budgets:renderBudgets,goals:renderGoals,recurring:renderRecurring,subscriptions:renderSubscriptions,reports:renderReports,settings:renderSettings};$('#page-content').innerHTML=renderers[state.page]();}
function periodTransactions(){const now=new Date();return state.transactions.filter(t=>{const d=new Date(`${t.date}T00:00:00`);if(state.period==='month')return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();if(state.period==='last-month'){const x=new Date(now.getFullYear(),now.getMonth()-1,1);return d.getMonth()===x.getMonth()&&d.getFullYear()===x.getFullYear()}if(state.period==='year')return d.getFullYear()===now.getFullYear();return true})}
function totals(rows){const income=rows.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount),0),expense=rows.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount),0);return{income,expense,savings:income-expense,rate:income?Math.round((income-expense)/income*100):0}}
function stat(label,value,note,icon,klass=''){return `<article class="card stat-card"><div class="stat-head"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-value ${klass}">${value}</div><div class="stat-note">${note}</div></article>`}
function renderDashboard(){const rows=periodTransactions(),t=totals(rows),balance=totals(state.transactions).savings;const cats={};rows.filter(x=>x.type==='expense').forEach(x=>cats[x.category]=(cats[x.category]||0)+Number(x.amount));const catRows=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,5);return `<div class="stats-grid">${stat('Total income',fmt(t.income),'For the selected period','↗','positive')}${stat('Total spending',fmt(t.expense),'For the selected period','↘','negative')}${stat('Savings',fmt(t.savings),'Income minus spending','⌁',t.savings>=0?'positive':'negative')}${stat('Savings rate',`${t.rate}%`,`${fmt(balance)} net cash flow all time`,'◎')}</div><div class="dashboard-grid"><section class="card panel"><div class="panel-head"><div><h2>Cash flow</h2><div class="panel-subtitle">Income and spending over the last 6 months</div></div><div class="legend"><span><i></i>Income</span><span><i class="expense"></i>Spending</span></div></div>${cashFlowChart()}<div class="chart-labels">${monthLabels()}</div></section><section class="card panel"><div class="panel-head"><div><h2>Spending by category</h2><div class="panel-subtitle">${state.period==='month'?'This month':'Selected period'}</div></div><button class="text-button" data-goto="reports">View report →</button></div>${catRows.length?`<div class="category-list">${catRows.map(([name,amount])=>`<div><div class="category-row-head"><span>${escapeHtml(name)}</span><span>${fmt(amount)}</span></div><div class="progress-track"><div class="progress-fill" style="width:${Math.max(3,amount/catRows[0][1]*100)}%"></div></div></div>`).join('')}</div>`:`<div class="category-empty">No spending recorded for this period.</div>`}</section></div><section class="section-head"><div><h2>Recent transactions</h2><p>Your latest income and spending</p></div><button class="text-button" data-goto="transactions">All transactions →</button></section>${transactionTable(state.transactions.slice(0,5),false)}`}
function monthLabels(){return Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-(5-i));return new Intl.DateTimeFormat('en',{month:'short'}).format(d)}).map(x=>`<span>${x}</span>`).join('')}
function cashFlowChart(){const groups=Array.from({length:6},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-(5-i));const rows=state.transactions.filter(t=>{const x=new Date(`${t.date}T00:00:00`);return x.getMonth()===d.getMonth()&&x.getFullYear()===d.getFullYear()});return totals(rows)}),max=Math.max(1,...groups.flatMap(g=>[g.income,g.expense]));const w=520,h=170;let grid='';for(let i=1;i<=3;i++){const y=h-i*h/4;grid+=`<line x1="0" x2="${w}" y1="${y}" y2="${y}" stroke="#edf0ed" stroke-dasharray="3 5"/>`}const bars=groups.map((g,i)=>{const x=30+i*82,ih=g.income/max*130,eh=g.expense/max*130;return `<rect x="${x}" y="${h-ih}" width="22" height="${ih}" rx="4" fill="#60a57b"><title>Income ${fmt(g.income)}</title></rect><rect x="${x+26}" y="${h-eh}" width="22" height="${eh}" rx="4" fill="#d7a077"><title>Spending ${fmt(g.expense)}</title></rect>`}).join('');return `<div class="chart"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="Monthly income and spending chart">${grid}${bars}</svg></div>`}
function transactionTable(rows,tools=true){if(!rows.length)return `<div class="card empty-state"><div class="empty-icon">↕</div><b>No transactions yet</b><p>Add your first income or expense to see your finances take shape.</p><button class="button primary" onclick="document.getElementById('quick-add').click()">＋ Add transaction</button></div>`;return `<div class="card table-card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Transaction</th><th>Category</th><th>Date</th><th>Account</th><th>Amount</th>${tools?'<th></th>':''}</tr></thead><tbody>${rows.map(t=>`<tr><td class="description-cell"><span class="tx-icon ${t.type==='expense'?'out':''}">${t.type==='income'?'↗':'↘'}</span>${escapeHtml(t.description)}</td><td><span class="pill">${escapeHtml(t.category||'Other')}</span></td><td>${new Date(`${t.date}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</td><td>${escapeHtml(t.account||'—')}</td><td class="${t.type==='income'?'positive':'negative'}">${t.type==='income'?'+':'−'}${fmt(t.amount)}</td>${tools?`<td class="row-actions"><button data-action="edit" data-kind="transaction" data-id="${t.id}">Edit</button><button data-action="delete" data-kind="transaction" data-id="${t.id}">Delete</button></td>`:''}</tr>`).join('')}</tbody></table></div></div>`}
function renderTransactions(){const rows=state.transactions.filter(t=>(state.filter==='all'||t.type===state.filter)&&(!state.search||`${t.description} ${t.category} ${t.account} ${t.notes}`.toLowerCase().includes(state.search.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date));return `<div class="section-head"><div><h2>Every transaction, in one place</h2><p>Record income and expenses as they happen.</p></div><div class="table-tools"><input class="search-input" id="transaction-search" placeholder="Search transactions…" value="${escapeHtml(state.search)}"><select id="transaction-filter" class="period-select"><option value="all" ${state.filter==='all'?'selected':''}>All types</option><option value="expense" ${state.filter==='expense'?'selected':''}>Expenses</option><option value="income" ${state.filter==='income'?'selected':''}>Income</option></select><button class="button primary" onclick="document.getElementById('quick-add').click()">＋ Add</button></div></div>${transactionTable(rows,true)}`}
function listEmpty(icon,title,copy,button){return `<div class="card empty-state"><div class="empty-icon">${icon}</div><b>${title}</b><p>${copy}</p>${button}</div>`}
function cardGrid(items,type){if(!items.length)return listEmpty(type==='budget'?'◎':type==='goal'?'⌁':type==='recurring'?'⟳':'▣',`No ${type==='budget'?'budgets':type==='goal'?'goals':type==='recurring'?'recurring items':'subscriptions'} yet`,`Add one to keep track of your ${type==='goal'?'savings plans':'planned money'}.`, `<button class="button primary" data-action="new" data-kind="${type}">＋ Add ${type}</button>`);return `<div class="cards-grid">${items.map(x=>itemCard(x,type)).join('')}</div>`}
function itemCard(x,type){const actions=`<div class="item-actions"><button data-action="edit" data-kind="${type}" data-id="${x.id}">Edit</button><button data-action="delete" data-kind="${type}" data-id="${x.id}">Delete</button></div>`;if(type==='budget'){const spent=periodTransactions().filter(t=>t.type==='expense'&&t.category===x.category).reduce((a,t)=>a+Number(t.amount),0),pct=Math.min(100,Math.round(spent/x.amount*100));return `<article class="card item-card"><div class="item-card-top"><div><h3>${escapeHtml(x.category)}</h3><div class="muted">Monthly limit</div></div><span class="pill">${pct}% used</span></div><div class="item-amount">${fmt(spent)} <span class="muted" style="font:11px 'DM Sans'">of ${fmt(x.amount)}</span></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%;background:${pct>=100?'#bc5748':pct>80?'#bd8a32':'#63a77e'}"></div></div><div class="item-footer"><span>${fmt(Math.max(0,x.amount-spent))} remaining</span>${actions}</div></article>`}if(type==='goal'){const pct=Math.min(100,Math.round(x.current_amount/x.target_amount*100));return `<article class="card item-card goal-card"><div class="item-card-top"><div style="text-align:left"><h3>${escapeHtml(x.name)}</h3><div class="muted">${x.target_date?`Target ${escapeHtml(x.target_date)}`:'Savings goal'}</div></div>${actions}</div><div class="goal-visual" style="--progress:${pct}%"><span>${pct}%</span></div><div class="item-meta"><span>Saved <b>${fmt(x.current_amount)}</b></span><span>Goal <b>${fmt(x.target_amount)}</b></span></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><div class="item-footer"><span>${fmt(Math.max(0,x.target_amount-x.current_amount))} to go</span></div></article>`}const when=x.next_date||x.due_date||'Date not set';return `<article class="card item-card"><div class="item-card-top"><div><h3>${escapeHtml(x.name)}</h3><div class="muted">${escapeHtml(x.frequency||x.category|| (type==='subscription'?'Subscription':'Recurring payment'))}</div></div>${actions}</div><div class="item-amount">${fmt(x.amount)} <span class="muted" style="font:11px 'DM Sans'">${type==='subscription'?'':'per '+escapeHtml(x.frequency||'month')}</span></div><div class="item-footer"><span>${type==='subscription'?'Next payment':'Next due'} · ${escapeHtml(when)}</span><span>${escapeHtml(x.account||'')}</span></div></article>`}
function renderBudgets(){return `<div class="section-head"><div><h2>Monthly category budgets</h2><p>Set a spending limit and see how much is left this month.</p></div><button class="button primary" data-action="new" data-kind="budget">＋ Add budget</button></div>${cardGrid(state.budgets,'budget')}`}
function renderGoals(){return `<div class="section-head"><div><h2>Your savings goals</h2><p>Small steps toward the things that matter to you.</p></div><button class="button primary" data-action="new" data-kind="goal">＋ Add goal</button></div>${cardGrid(state.goals,'goal')}`}
function renderRecurring(){return `<div class="section-head"><div><h2>Recurring payments</h2><p>Manually list regular bills and payments. Ledgerly does not detect these automatically.</p></div><button class="button primary" data-action="new" data-kind="recurring">＋ Add payment</button></div>${cardGrid(state.recurring,'recurring')}`}
function renderSubscriptions(){return `<div class="section-head"><div><h2>Subscriptions</h2><p>Keep your memberships and renewals visible with manual entries.</p></div><button class="button primary" data-action="new" data-kind="subscription">＋ Add subscription</button></div>${cardGrid(state.subscriptions,'subscription')}`}
function renderReports(){const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-(5-i));return{date:d,label:new Intl.DateTimeFormat('en',{month:'short'}).format(d)}});const vals=months.map(({date,label})=>{const r=state.transactions.filter(t=>{const d=new Date(`${t.date}T00:00:00`);return d.getMonth()===date.getMonth()&&d.getFullYear()===date.getFullYear()});return{label,...totals(r)}}),max=Math.max(1,...vals.flatMap(x=>[x.income,x.expense]));const categories={};state.transactions.filter(t=>t.type==='expense').forEach(t=>categories[t.category]=(categories[t.category]||0)+Number(t.amount));const cats=Object.entries(categories).sort((a,b)=>b[1]-a[1]).slice(0,7);return `<div class="section-head"><div><h2>Your money, over time</h2><p>A simple view of income, spending, and where it goes.</p></div></div><div class="report-grid"><section class="card report-card"><h2>Income vs spending</h2><div class="panel-subtitle">Last six months · <span class="legend"><i></i>Income <i class="expense"></i>Spending</span></div><div class="report-bars">${vals.map(v=>`<div class="report-month"><div class="bar-pair"><div class="bar" style="height:${v.income/max*100}%"><title>${fmt(v.income)}</title></div><div class="bar expense" style="height:${v.expense/max*100}%"><title>${fmt(v.expense)}</title></div></div>${v.label}</div>`).join('')}</div><div class="report-summary"><div><span>6 month income</span><b class="positive">${fmt(vals.reduce((a,x)=>a+x.income,0))}</b></div><div><span>6 month spending</span><b class="negative">${fmt(vals.reduce((a,x)=>a+x.expense,0))}</b></div><div><span>Net savings</span><b>${fmt(vals.reduce((a,x)=>a+x.savings,0))}</b></div></div></section><section class="card report-card"><h2>Spending by category</h2><div class="panel-subtitle">All recorded expense transactions</div><div class="category-list" style="margin-top:25px">${cats.length?cats.map(([name,amount])=>`<div><div class="category-row-head"><span>${escapeHtml(name)}</span><span>${fmt(amount)}</span></div><div class="progress-track"><div class="progress-fill" style="width:${amount/cats[0][1]*100}%"></div></div></div>`).join(''):'<div class="category-empty">Category totals will appear after you add an expense.</div>'}</div></section></div>`}
function renderSettings(){return `<div class="section-head"><div><h2>Settings</h2><p>Make Ledgerly work the way you do.</p></div></div><div class="settings-layout"><div class="card settings-nav">${[['categories','Categories'],['accounts','Accounts'],['data','Data & privacy']].map(([id,name])=>`<button data-action="settings-tab" data-id="${id}" class="${state.settingsTab===id?'active':''}">${name}</button>`).join('')}</div><section class="card settings-content">${settingsContent()}</section></div>`}
function settingsContent(){if(state.settingsTab==='categories'||state.settingsTab==='accounts'){const cats=state.settingsTab==='categories',values=state[cats?'categories':'accounts'];return `<h2>${cats?'Categories':'Accounts & methods'}</h2><p>${cats?'Choose labels for organizing income and expenses.':'Manage the accounts or payment methods you use.'}</p><div class="settings-data-list">${values.map(x=>`<span class="settings-chip">${escapeHtml(typeof x==='string'?x:x.name)}${x.id?`<button aria-label="Remove" data-action="delete" data-kind="${cats?'category':'account'}" data-id="${x.id}">×</button>`:''}</span>`).join('')}</div><button class="button secondary" data-action="new" data-kind="${cats?'category':'account'}">＋ Add ${cats?'category':'account'}</button>`}return `<h2>Data & privacy</h2><p>Your records are stored in your Supabase account and protected by row-level security.</p><div class="settings-row"><div><b>Currency</b><small>Ledgerly currently displays amounts in Indian Rupees.</small></div><span class="pill">INR · ₹</span></div><div class="settings-row"><div><b>Export transactions</b><small>Download a CSV copy of your transactions.</small></div><button class="button secondary" data-action="export">Export CSV</button></div><div class="settings-row"><div><b>Import transactions</b><small>Import a CSV with date, type, description, amount, category, account, notes.</small></div><label class="button secondary" for="csv-file">Choose CSV<input id="csv-file" type="file" accept=".csv,text/csv" hidden></label></div><div class="settings-row"><div><b>Delete all my data</b><small>Permanently remove all financial records from your account.</small></div><button class="button danger" data-action="wipe">Delete all data</button></div>`}

function transactionCategories(){const names=state.categories.map(c=>typeof c==='string'?c:c.name);return names.length?names:defaultCategories}
function openTransaction(item){$('#transaction-form').reset();$('#transaction-id').value=item?.id||'';$('#transaction-heading').textContent=item?'Edit transaction':'Add transaction';$('#tx-description').value=item?.description||'';$('#tx-amount').value=item?.amount||'';$('#tx-date').value=item?.date||isoToday();$('#tx-notes').value=item?.notes||'';$('#tx-account').value=item?.account||'';$('#tx-category').innerHTML=transactionCategories().map(c=>`<option>${escapeHtml(c)}</option>`).join('');$('#tx-category').value=item?.category||transactionCategories()[0];const radio=$(`input[name="tx-type"][value="${item?.type||'expense'}"]`);if(radio)radio.checked=true;$('#transaction-dialog').showModal()}
async function saveTransaction(e){e.preventDefault();const id=$('#transaction-id').value;const tx={type:$('input[name="tx-type"]:checked').value,description:$('#tx-description').value.trim(),amount:Number($('#tx-amount').value),date:$('#tx-date').value,category:$('#tx-category').value,account:$('#tx-account').value.trim(),notes:$('#tx-notes').value.trim()};const response=id?await db.from('transactions').update(tx).eq('id',id).select().single():await db.from('transactions').insert(tx).select().single();if(response.error){message(response.error.message,true);return}if(id)state.transactions=state.transactions.map(x=>x.id===id?response.data:x);else state.transactions.unshift(response.data);$('#transaction-dialog').close();render();message(id?'Transaction updated.':'Transaction added.')}
const schemas={budget:{label:'Monthly budget',table:'budgets',fields:[['category','Category','category'],['amount','Monthly limit (₹)','number']]},goal:{label:'Savings goal',table:'goals',fields:[['name','Goal name','text'],['target_amount','Target amount (₹)','number'],['current_amount','Already saved (₹)','number'],['target_date','Target date','date']]},recurring:{label:'Recurring payment',table:'recurring',fields:[['name','Payment name','text'],['amount','Amount (₹)','number'],['frequency','Frequency','frequency'],['next_date','Next due date','date'],['account','Account / method','text']]},subscription:{label:'Subscription',table:'subscriptions',fields:[['name','Subscription name','text'],['amount','Amount (₹)','number'],['frequency','Billing frequency','frequency'],['next_date','Next renewal','date'],['account','Payment method','text']]},category:{label:'Category',table:'categories',fields:[['name','Category name','text']]},account:{label:'Account',table:'accounts',fields:[['name','Account or method name','text']]}};
function openSimple(kind,item){const schema=schemas[kind];$('#simple-form').reset();$('#simple-id').value=item?.id||'';$('#simple-heading').textContent=`${item?'Edit':'Add'} ${schema.label.toLowerCase()}`;$('#simple-eyebrow').textContent=schema.label.toUpperCase();$('#simple-fields').innerHTML=schema.fields.map(([key,label,type])=>{if(type==='category')return `<label>${label}<select id="simple-${key}" required>${transactionCategories().map(n=>`<option>${escapeHtml(n)}</option>`).join('')}</select></label>`;if(type==='frequency')return `<label>${label}<select id="simple-${key}" required>${['Weekly','Monthly','Quarterly','Yearly'].map(n=>`<option>${n}</option>`).join('')}</select></label>`;return `<label class="${schema.fields.length===1?'wide':''}">${label}<input id="simple-${key}" type="${type}" ${type==='number'?'min="0.01" step="0.01"':''} ${key==='current_amount'?'min="0"':''} ${key==='target_date'||key==='next_date'?'':'required'}></label>`}).join('');schema.fields.forEach(([key])=>{const el=$(`#simple-${key}`);if(el&&item?.[key]!=null)el.value=item[key]});if(kind==='budget'&&!item)$('#simple-category').value=transactionCategories()[0];$('#simple-dialog').showModal()}
async function saveSimple(e){e.preventDefault();const kind=$('#simple-form').dataset.kind,id=$('#simple-id').value,schema=schemas[kind],payload={};for(const [key,,type] of schema.fields){const el=$(`#simple-${key}`);payload[key]=type==='number'?Number(el.value||0):el.value.trim()}const response=id?await db.from(schema.table).update(payload).eq('id',id).select().single():await db.from(schema.table).insert(payload).select().single();if(response.error){message(response.error.message,true);return}if(id)state[schema.table]=state[schema.table].map(x=>x.id===id?response.data:x);else state[schema.table].unshift(response.data);$('#simple-dialog').close();render();message(`${schema.label} saved.`)}
async function handleAction(action,id,kind){if(action==='new'){if(kind==='transaction')return openTransaction();$('#simple-form').dataset.kind=kind;return openSimple(kind)}if(action==='edit'){if(kind==='transaction')return openTransaction(state.transactions.find(x=>x.id===id));const table=schemas[kind]?.table;$('#simple-form').dataset.kind=kind;return openSimple(kind,state[table]?.find(x=>x.id===id))}if(action==='delete'){const table=kind==='transaction'?'transactions':schemas[kind]?.table;if(!table)return;state.pendingDelete=[kind,id,table];$('#confirm-title').textContent=`Delete this ${kind==='transaction'?'transaction':kind}?`;$('#confirm-copy').textContent='This will permanently remove this item from your Ledgerly account.';$('#confirm-action').textContent='Delete';$('#confirm-dialog').showModal()}if(action==='settings-tab'){state.settingsTab=id;render()}if(action==='export')exportCsv();if(action==='wipe')wipeData();}
async function deleteItem(kind,id,table){const {error}=await db.from(table).delete().eq('id',id);if(error){message(error.message,true);return}state[table]=state[table].filter(x=>x.id!==id);render();message('Item deleted.')}
function exportCsv(){const cols=['date','type','description','amount','category','account','notes'];const csv=[cols.join(','),...state.transactions.map(t=>cols.map(k=>`"${String(t[k]??'').replaceAll('"','""')}"`).join(','))].join('\r\n');download(csv,'ledgerly-transactions.csv','text/csv');message('Transactions exported.')}
function download(content,name,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===','){row.push(field);field=''}else if(c==='\n'){row.push(field);rows.push(row);row=[];field=''}else if(c!=='\r')field+=c}if(field||row.length){row.push(field);rows.push(row)}return rows}
document.addEventListener('change',async e=>{if(e.target.id!=='csv-file'||!e.target.files[0])return;try{const rows=parseCsv(await e.target.files[0].text());const heads=rows.shift().map(h=>h.trim().toLowerCase());const records=rows.filter(r=>r.length>1).map(r=>Object.fromEntries(heads.map((h,i)=>[h,(r[i]||'').trim()]))).map(r=>({date:r.date,type:r.type,description:r.description,amount:Number(r.amount),category:r.category||'Other',account:r.account||'',notes:r.notes||''}));if(records.some(r=>!r.date||!['income','expense'].includes(r.type)||!r.description||!r.amount||Number.isNaN(r.amount)))throw Error('CSV needs date, type (income/expense), description, and a positive amount on every row.');const {data,error}=await db.from('transactions').insert(records).select();if(error)throw error;state.transactions.unshift(...data);render();message(`${data.length} transaction${data.length===1?'':'s'} imported.`)}catch(err){message(`Import failed: ${err.message}`,true)}finally{e.target.value=''}});
async function wipeData(){state.pendingDelete=['wipe','all',null];$('#confirm-title').textContent='Delete all your financial data?';$('#confirm-copy').textContent='This permanently deletes transactions, budgets, goals, recurring payments, subscriptions, accounts, and custom categories. This cannot be undone.';$('#confirm-action').textContent='Delete everything';$('#confirm-dialog').showModal();$('#confirm-action').onclick=async ev=>{ev.preventDefault();$('#confirm-dialog').close();for(const t of ['transactions','budgets','goals','recurring','subscriptions','accounts','categories']){const {error}=await db.from(t).delete().not('id','is',null);if(error){message(`Could not clear ${t}: ${error.message}`,true);return}}await loadAll();render();message('Your financial records have been deleted.')}}
init();
